name: .NET Tests

on:
  push:
    branches:
      - master  # ou nome da sua branch principal
  pull_request:
    branches:
      - master  # ou nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: 
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --verbosity normal --configuration Release --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=lcov \
          /p:CoverletOutput=/home/runner/work/WakeProductAPI/WakeProductAPI/Test/ProductControllerTests/TestResults/Coverage/
    
    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: TestResults

    - name: Publish Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: Coverage
        path: $(Build.SourcesDirectory)/TestResults/Coverage/
