name: .NET Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ProductAPI/ProductAPI.csproj

    - name: Build
      run: dotnet build ProductAPI/ProductAPI.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test